# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /:title

# Setup
title: hy
tagline: 'blog'
description: ''
url: https://namadomainmu.com
baseurl: ""

author:
  name: 'M Hy'
  url: https://twitter.com/hy

paginate: 5

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom vars
version: 2.1.0
