# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:title
relative_permalinks: true

# Setup
title:            hy
tagline:          'blog'
description:      'boog'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'M Hy'
  url:            https://twitter.com/hy

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
